name: build docs
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -q --no-install-recommends doxygen
          pip install flit
          pip install -e ".[doc]"
      - name: generate templates
        run: |
          doxybook-c generate-templates
      - name: generate c api
        run: |
          pushd example/c
          doxygen
          doxybook-c -i temp/xml -o docs --template-dir ../../templates --template-lang c
          popd
      - name: generate cpp api
        run: |
          pushd example/cpp
          doxygen
          doxybook-c -i temp/xml -o docs --template-dir ../../templates --template-lang cpp
          popd
      - name: deploy mkdocs
        run: |
          mkdocs gh-deploy --force
      - uses: actions/upload-artifact@v3
        with:
          name: api-reference
          path: |
            example/c/docs/api.md
            example/cpp/docs/api.md
          if-no-files-found: error
