name: build docs
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          sudo apt-get update
          sudo apt-get install -y -q --no-install-recommends doxygen
      - run: |
          pip install flit
          pip install -e ".[doc]"
      - run: |
          cd example
          doxygen
          # use template
          doxybook-c generate-templates
          doxybook-c -i temp/xml -o docs --template-dir ./templates
          mkdocs gh-deploy --force
      - uses: actions/upload-artifact@v3
        with:
          name: api-reference
          path: example/docs/api.md
          if-no-files-found: error
